---
title: "Interactive Map 2"
output: html_notebook
runtime: shiny
---

# Minimum working example of interactive map

##Load Packages
```{r}
library(rgdal)     # R wrapper around GDAL/OGR
library(dplyr)     # Data manipulation  
library(shiny)     # Make the app     
library(leaflet)   # Interactive maps with pop-ups          
library(sp)        # Used to merge shape file and data frame
```

## Data
```{r}
provIndo <- 
    readOGR("/Users/User/Desktop/UNICEF/Maps/shape", "IDN_adm1") # Shapefile 

df = read.csv(file = "/Users/User/Desktop/R Prac/UNICEF Project/SDG.csv", sep=",") # SDG Data

SDG = df[,colSums(is.na(df)) != nrow(df)] # Remove empty columns

SDG1 <- SDG %>%
        select("SDG" = "SDG.Goal", "Indicator" = "Indicator", "Value" = "Value", "Province" = "Province") # Rename the variables to make them easier to work with and select the ones that apply to our needs

SDGdf <- SDG1 %>%
        filter(Province != "All Indonesia") # Remove all national level data

idName <- SDGdf %>% #Bind province names from the dataset to their numeric equivalents in the shapefile- ID_1
        mutate(id = ifelse(Province == "Aceh", 0, ifelse(Province == "Bali", 1, ifelse(Province == "Banten", 3, ifelse(Province == "Bengkulu", 4, ifelse(Province == "DI Yogyakarta", 33, ifelse(Province == "DKI Jakarta", 7, ifelse(Province == "Gorontalo", 5, ifelse(Province == "Jambi", 8, ifelse(Province == "Jawa Barat", 9, ifelse(Province == "Jawa Tengah", 10, ifelse(Province == "Jawa Timur", 11, ifelse(Province == "Kalimantan Barat", 12, ifelse(Province == "Kalimantan Selatan", 13, ifelse(Province == "Kalimantan Tengah", 14, ifelse(Province == "Kalimantan Timur", 15, ifelse(Province == "Kalimantan Utara", 16, ifelse(Province == "Kepulauan Bangka Belitung", 2,  ifelse(Province == "Kepulauan Riau", 17, ifelse(Province == "Lampung", 18, ifelse(Province == "Maluku", 20, ifelse(Province == "Maluku Utara", 19, ifelse(Province == "Nusa Tenggara Barat", 21,  ifelse(Province == "Nusa Tenggara Timur", 22, ifelse(Province == "Papua", 23, ifelse(Province == "Papua Barat", 6, ifelse(Province == "Riau", 24, ifelse(Province == "Sulawesi Barat", 25,  ifelse(Province == "Sulawesi Selatan", 26, ifelse(Province == "Sulawesi Tengah", 27, ifelse(Province == "Sulawesi Tenggara", 28, ifelse(Province == "Sulawesi Utara", 29, ifelse(Province == "Sumatera Barat", 30, ifelse(Province == "Sumatera Selatan", 31, 32)))))))))))))))))))))))))))))))))) # "Sumatera Utara" left out of ifelse statement!

idName1 <- idName%>% # In previous iteration, numbers were from 0-33, now they are 1-34 so add 1 to each of the numbers to match
        mutate(ID_1 = id + 1)

SDG1 <- idName1 %>% 
        filter(Indicator == "Proportion of population living below the national poverty line") # Filter the dataframe so that it is only data for a selected indicator

oo <- merge(provIndo, SDG1, by="ID_1") # Merge the shape file and the dataframe

oo$Value <- as.numeric(as.character(oo$Value)) # Convert the 'Value' variable from a factor to a numeric data class
```

## Make sure that the shape file is not broken!
```{r}
#plot(oo)
```
If a map of Indonesia is returned, the polygons from the shapefile is still intact!

## What are the map boundaries?
```{r}
bnds <- provIndo@bbox
long <- (bnds[1,1]-bnds[1,2]/2) + bnds[1,1]
lat <- (bnds[2,1]-bnds[2,2]/2) - bnds[2,1]
```


## Color palette and data binning the data
```{r}
UNICEF <- c('#00689D','#DDA63A', '#C5192D', '#F1F1F1') #Blue, Orange, Red, Grey

no_classes <- 4 # Number of data ranges

bins <- quantile(oo$Value, 
                      probs = seq(0, 1, length.out = no_classes + 1)) # Generate quantile ranges to map

pal <- colorBin(UNICEF, domain = oo$Value, bins = bins) # Define palette
```

## Generating the interactive map
```{r}
labels <- sprintf( # Define what should come up in the pop-up
  "<strong>%s</strong><br/>%g &#37",
  oo$Province, oo$Value
) %>% lapply(htmltools::HTML)

m <- leaflet(oo) %>% 
        addPolygons( # From the shape file, what to map
                fillColor = ~pal(Value), # choropleth colours
                weight = .5, # Thickness of province border lines
                opacity = 1, # Opacity of border lines
                color = "white", # Colour of province border lines
                dashArray = "", # Border line type, solid/dashed/etc.
                fillOpacity = 0.7, # Opacity of choropleth colors
                highlight = highlightOptions( # Pop-up options
                         weight = 2, # Thickness of pop-up boundaries
                         color = "#666", # Colour of pop-up boundaries
                         dashArray = "", # Line type for pop-up boundaries
                         fillOpacity = 0.7, # Opacity of pop-up boundaries 
                         bringToFront = TRUE), # Bring the pop-up boundaries in front of the border lines?
                label = labels, # Labels defined above
                        labelOptions = labelOptions( # Options for the text inside the pop-up
                        style = list("font-weight" = "normal", padding = "3px 8px"), # Text style options
                        textsize = "15px", # Text size
                        direction = "auto"))%>% # Left aligned, starting at upper left
        
        addLegend(pal = pal, values = ~Value, opacity = 0.7, title = NULL,
  position = "bottomleft") # Legend options

m %>% # Print map 
        setView(long, lat, zoom = 4) # Define map boundaries
```
